trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: run
  displayName: 'Run the conditional task'
  type: boolean
  default: false

jobs:
- job: ConditionalJob
  displayName: 'Conditional Job'
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: echo "This task always runs."
    displayName: 'Always Run Task'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
    displayName: 'Use Python 3.x'
    condition: eq('${{ parameters.run }}', true)