name: approval_job_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildStage
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    - script: echo "Building the project..."
      displayName: 'Build Step'

- stage: ApprovalStage
  dependsOn: BuildStage
  jobs:
  - deployment: 'deploy_after_aprove'
    environment:
      name: qa
    displayName: 'Approval Job'
    strategy:
     runOnce:
      deploy:
        steps:
        - script: echo "This job will run after manual approval."
          displayName: 'Post-Approval Step'